
services:
  nginx:
    image: nginx:alpine
    container_name: crud-laravel-nginx
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: crud-laravel-php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel-network
      - databases
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  laravel-network:
    driver: bridge
    external: false
  databases:
    external: true
    name: shared_wobz_network

